# Generated by Django 6.0.6 on 2026-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('price_per_km', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
