# Generated by Django 6.0.6 on 2026-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
