# Generated by Django 6.0.6 on 2026-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='cab_type',
            field=models.CharField(default='mini', max_length=20),
            preserve_default=False,
        ),
    ]
