# Generated by Django 6.0.6 on 2026-07-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cab_cab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_cab',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
